# config.sub
# Autogenerated from man page /usr/share/man/man1/config.sub.1.gz
complete -c 'config.sub' -s h -l help -d 'print this help, then exit'
complete -c 'config.sub' -s t -l time-stamp -d 'print date of last modification, then exit'
complete -c 'config.sub' -s v -l version -d 'print version number, then exit REPORTING BUGS Report bugs and patches to <co…'

