# debconf-updatepo
# Autogenerated from man page /usr/share/man/man1/debconf-updatepo.1.gz
complete -c debconf-updatepo -s h -l help -d 'Display a usage summary and exit'
complete -c debconf-updatepo -s v -l verbose -d 'Process in verbose mode'
complete -c debconf-updatepo -l podir -d 'Set directory for \\s-1PO\\s0 files'
complete -c debconf-updatepo -l skip-pot -d 'Do not generate a new po/templates. pot file'
complete -c debconf-updatepo -l skip-merge -d 'Do not merge existing \\s-1PO\\s0 files with po/templates. pot'
complete -c debconf-updatepo -l msgid-bugs-address -d 'Set the email address that will be specified in the \\s-1POT\\s0\'s Report-Msgid…'

