# dh_autoreconf
# Autogenerated from man page /usr/share/man/man1/dh_autoreconf.1.gz
complete -c dh_autoreconf -o Xitem -l exclude -d 'Exclude files that contain \\*(L"item\\*(R" anywhere in their filename from bei…'
complete -c dh_autoreconf -l mode -d 'Change the way in which modifications to files are detected'
complete -c dh_autoreconf -l as-needed -d 'Enable support for -Wl,--as-needed in all ltmain'
complete -c dh_autoreconf -o Ddir -l sourcedirectory -d 'Run everything in the source directory'

