# dh_clean
# Autogenerated from man page /usr/share/man/man1/dh_clean.1.gz
complete -c dh_clean -s k -l keep -d 'This is deprecated, use dh_prep\\|(1) instead'
complete -c dh_clean -s d -l dirs-only -d 'Only clean the package build directories, do not clean up any other files at …'
complete -c dh_clean -o Xitem -l exclude -d 'Exclude files that contain item anywhere in their filename from being deleted…'

