# dh_installexamples
# Autogenerated from man page /usr/share/man/man1/dh_installexamples.1.gz
complete -c dh_installexamples -s A -l all -d 'Install any files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_installexamples -l sourcedir -d 'Look in the specified directory for files to be installed'
complete -c dh_installexamples -l doc-main-package -d 'Set the main package for a documentation package'
complete -c dh_installexamples -o Xitem -l exclude -d 'Exclude files that contain item anywhere in their filename from being install…'

