# dh_installdocs
# Autogenerated from man page /usr/share/man/man1/dh_installdocs.1.gz
complete -c dh_installdocs -s A -l all -d 'Install all files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_installdocs -o Xitem -l exclude -d 'Exclude files that contain item anywhere in their filename from being install…'
complete -c dh_installdocs -l sourcedir -d 'Look in the specified directory for files to be installed'
complete -c dh_installdocs -l doc-main-package -d 'Set the main package for a documentation package'
complete -c dh_installdocs -l link-doc -d 'Make the documentation directory of all packages acted on be a symlink to the…'

