# dh_installwm
# Autogenerated from man page /usr/share/man/man1/dh_installwm.1.gz
complete -c dh_installwm -l priority -d 'Set the priority of the window manager'
complete -c dh_installwm -s n -l no-scripts -d 'Do not modify postinst/prerm scripts.  Turns this command into a no-op'
complete -c dh_installwm -s A -l all -d 'Modify scripts for window managers specified by command line parameters in \\s…'

