# dh_installemacsen
# Autogenerated from man page /usr/share/man/man1/dh_installemacsen.1.gz
complete -c dh_installemacsen -s n -l no-scripts -d 'Do not modify postinst/prerm scripts'
complete -c dh_installemacsen -l priority -d 'Sets the priority number of a site-start. d file.  Default is 50'

