# dh_link
# Autogenerated from man page /usr/share/man/man1/dh_link.1.gz
complete -c dh_link -s A -l all -d 'Create any links specified by command line parameters in \\s-1ALL\\s0 packages …'
complete -c dh_link -o Xitem -l exclude -d 'Exclude symlinks that contain item anywhere in their filename from being corr…'

