# dh_shlibdeps
# Autogenerated from man page /usr/share/man/man1/dh_shlibdeps.1.gz
complete -c dh_shlibdeps -o Xitem -l exclude -d 'Exclude files that contain item anywhere in their filename from being passed …'
complete -c dh_shlibdeps -o uparams -l dpkg-shlibdeps-params -d 'This is another way to pass params to dpkg-shlibdeps\\|(1)'
complete -c dh_shlibdeps -o 'ldirectory[:directory' -d 'With recent versions of dpkg-shlibdeps, this option is generally not needed'

