# dh_strip
# Autogenerated from man page /usr/share/man/man1/dh_strip.1.gz
complete -c dh_strip -o Xitem -l exclude -d 'Exclude files that contain item anywhere in their filename from being stripped'
complete -c dh_strip -l dbg-package -d 'This option is a now special purpose option that you normally do not need'
complete -c dh_strip -s k -l keep-debug -d 'This option is a now special purpose option that you normally do not need'
complete -c dh_strip -l dbgsym-migration -d 'This option is used to migrate from a manual \\*(L"-dbg\\*(R" package (created …'
complete -c dh_strip -l automatic-dbgsym -l no-automatic-dbgsym -d 'Control whether dh_strip should be creating debug symbol packages when possib…'
complete -c dh_strip -l ddebs -l no-ddebs -d 'Historical name for --automatic-dbgsym and --no-automatic-dbgsym'

