# gp-archive
# Autogenerated from man page /usr/share/man/man1/gp-archive.1.gz
complete -c gp-archive -l version -d 'print the version number and exit'
complete -c gp-archive -l help -d 'print usage information and exit'
complete -c gp-archive -l verbose -d 'enable (on) or disable (off) verbose mode; the default is "off"'
complete -c gp-archive -s a -d 'specify archiving of binaries and other files; in addition to disable this fe…'
complete -c gp-archive -s n -d 'archive the named experiment only, not any of its descendants'
complete -c gp-archive -s q -d 'do not write any warnings to stderr; messages are archived and can be retriev…'
complete -c gp-archive -s F -d 'force writing or rewriting of the archive; ignored with the -n or -m options,…'
complete -c gp-archive -s d -d 'specifies the location of a common archive; this is a directory that contains…'
complete -c gp-archive -s m -d 'archive only those source, object, and debug info files whose full path name …'

