# gprofng
# Autogenerated from man page /usr/share/man/man1/gprofng.1.gz
complete -c gprofng -l version -d 'print the version number and exit'
complete -c gprofng -l help -d 'print usage information and exit'
complete -c gprofng -l check -d 'verify if the hardware and software environment is supported'
complete -c gprofng -l verbose -d 'enable (on) or disable (off) verbose mode; the default is "off"'

