# mkcert
# Autogenerated from man page /usr/share/man/man1/mkcert.1.gz
complete -c mkcert -o cert-file -o key-file -o p12-file -d 'Customize the output paths'
complete -c mkcert -o client -d 'Generate a certificate for client authentication'
complete -c mkcert -o ecdsa -d 'Generate a certificate with an ECDSA key'
complete -c mkcert -o pkcs12 -d 'Generate a ". p12" PKCS #12 file, also know as a "'
complete -c mkcert -o csr -d 'Generate a certificate based on the supplied CSR'
complete -c mkcert -o CAROOT -d 'Print the CA certificate and key storage location'

