# peardev
# Autogenerated from man page /usr/share/man/man1/peardev.1.gz
complete -c peardev -s v -d 'increase verbosity level (default 1)'
complete -c peardev -s q -d 'be quiet, decrease verbosity level'
complete -c peardev -s c -d 'find user configuration in file'
complete -c peardev -s C -d 'find system configuration in file'
complete -c peardev -s d -d 'set user config variable foo to bar'
complete -c peardev -s D -d 'set system config variable foo to bar'
complete -c peardev -s G -d 'start in graphical (Gtk) mode'
complete -c peardev -s S -d 'store system configuration'
complete -c peardev -s s -d 'store user configuration'
complete -c peardev -s y -d 'unset  foo in the user configuration'
complete -c peardev -s V -d 'version information'
complete -c peardev -s h
complete -c peardev -s '?' -d 'display help/usage'

