# pear
# Autogenerated from man page /usr/share/man/man1/pear.1.gz
complete -c pear -s v -d 'increase verbosity level (default 1)'
complete -c pear -s q -d 'be quiet, decrease verbosity level'
complete -c pear -s c -d 'find user configuration in file'
complete -c pear -s C -d 'find system configuration in file'
complete -c pear -s d -d 'set user config variable foo to bar'
complete -c pear -s D -d 'set system config variable foo to bar'
complete -c pear -s G -d 'start in graphical (Gtk) mode'
complete -c pear -s S -d 'store system configuration'
complete -c pear -s s -d 'store user configuration'
complete -c pear -s y -d 'unset  foo in the user configuration'
complete -c pear -s V -d 'version information'
complete -c pear -s h
complete -c pear -s '?' -d 'display help/usage'

