# pecl
# Autogenerated from man page /usr/share/man/man1/pecl.1.gz
complete -c pecl -s v -d 'increase verbosity level (default 1)'
complete -c pecl -s q -d 'be quiet, decrease verbosity level'
complete -c pecl -s c -d 'find user configuration in file'
complete -c pecl -s C -d 'find system configuration in file'
complete -c pecl -s d -d 'set user config variable foo to bar'
complete -c pecl -s D -d 'set system config variable foo to bar'
complete -c pecl -s G -d 'start in graphical (Gtk) mode'
complete -c pecl -s S -d 'store system configuration'
complete -c pecl -s s -d 'store user configuration'
complete -c pecl -s y -d 'unset  foo in the user configuration'
complete -c pecl -s V -d 'version information'
complete -c pecl -s h
complete -c pecl -s '?' -d 'display help/usage'

