# php-config8.3
# Autogenerated from man page /usr/share/man/man1/php-config8.3.1.gz
complete -c 'php-config8.3' -l prefix -d 'Directory prefix where PHP is installed, e. g.  /usr/local'
complete -c 'php-config8.3' -l includes -d 'List of -I options with all include files'
complete -c 'php-config8.3' -l ldflags -d 'LD Flags which PHP was compiled with'
complete -c 'php-config8.3' -l libs -d 'Extra libraries which PHP was compiled with'
complete -c 'php-config8.3' -l man-dir -d 'The directory prefix where the manpages is installed'
complete -c 'php-config8.3' -l extension-dir -d 'Directory where extensions are searched by default'
complete -c 'php-config8.3' -l include-dir -d 'Directory prefix where header files are installed by default'
complete -c 'php-config8.3' -l php-binary -d 'Full path to php CLI or CGI binary'
complete -c 'php-config8.3' -l php-sapis -d 'Show all SAPI modules installed on the Debian system'
complete -c 'php-config8.3' -l configure-options -d 'Configure options to recreate configuration of current PHP installation'
complete -c 'php-config8.3' -l version -d 'PHP version'
complete -c 'php-config8.3' -l vernum -d 'PHP version as integer SEE ALSO php (1) VERSION INFORMATION This manpage desc…'

