# php-fpm8.4
# Autogenerated from man page /usr/share/man/man8/php-fpm8.4.8.gz
complete -c 'php-fpm8.4' -s C -d 'Do not chdir to the script\'s directory'
complete -c 'php-fpm8.4' -s c -d 'Look for  php. ini file in the directory R path or use the specified R file'
complete -c 'php-fpm8.4' -s n -d 'No  php. ini file will be used'
complete -c 'php-fpm8.4' -s d -d 'Define INI entry R foo with value R bar'
complete -c 'php-fpm8.4' -s e -d 'Generate extended information for debugger/profiler'
complete -c 'php-fpm8.4' -s h -d 'This help'
complete -c 'php-fpm8.4' -s i -d 'PHP information and configuration'
complete -c 'php-fpm8.4' -s m -d 'Show compiled in modules'
complete -c 'php-fpm8.4' -s v -d 'Version number'
complete -c 'php-fpm8.4' -s p -d 'Specify alternative prefix path (the default is /usr)'
complete -c 'php-fpm8.4' -s g -d 'Specify the PID file location'
complete -c 'php-fpm8.4' -s y -d 'Specify alternative path to FastCGI process manager configuration file (the d…'
complete -c 'php-fpm8.4' -s t -d 'Test FPM configuration file and exit If called twice (-tt), the configuration…'
complete -c 'php-fpm8.4' -s D -d 'Force to run in background and ignore daemonize option from configuration file'
complete -c 'php-fpm8.4' -s F -d 'Force to stay in foreground and ignore daemonize option from configuration fi…'
complete -c 'php-fpm8.4' -s O -d 'Force output to stderr in nodaemonize even if stderr is not a TTY'
complete -c 'php-fpm8.4' -l php-ini
complete -c 'php-fpm8.4' -l no-php-ini
complete -c 'php-fpm8.4' -l define
complete -c 'php-fpm8.4' -l help
complete -c 'php-fpm8.4' -l info
complete -c 'php-fpm8.4' -l modules
complete -c 'php-fpm8.4' -l version
complete -c 'php-fpm8.4' -l prefix
complete -c 'php-fpm8.4' -l pid
complete -c 'php-fpm8.4' -l fpm-config
complete -c 'php-fpm8.4' -l test
complete -c 'php-fpm8.4' -l daemonize
complete -c 'php-fpm8.4' -l nodaemonize
complete -c 'php-fpm8.4' -l force-stderr
complete -c 'php-fpm8.4' -l allow-to-run-as-root
complete -c 'php-fpm8.4' -s R -d 'Allow pool to run as root (disabled by default) FILES'

