# phpabtpl
# Autogenerated from man page /usr/share/man/man1/phpabtpl.1.gz
complete -c phpabtpl -s h -l help -d 'Print a help message and exit'
complete -c phpabtpl -l basedir -d 'Set the base directory for \\*(L"files\\*(R" autoloading'
complete -c phpabtpl -l require -d 'Adds an additional required dependency to be loaded'
complete -c phpabtpl -l suggest -d 'Adds an additional suggested dependency to be (optionally) loaded'

