# phpize8.4
# Autogenerated from man page /usr/share/man/man1/phpize8.4.1.gz
complete -c 'phpize8.4' -l clean -d 'Remove all created files'
complete -c 'phpize8.4' -l help -d 'Prints usage information'
complete -c 'phpize8.4' -l version
complete -c 'phpize8.4' -s v -d 'Prints API version information SEE ALSO php (1) VERSION INFORMATION This manp…'

