# phpize8.3
# Autogenerated from man page /usr/share/man/man1/phpize8.3.1.gz
complete -c 'phpize8.3' -l clean -d 'Remove all created files'
complete -c 'phpize8.3' -l help -d 'Prints usage information'
complete -c 'phpize8.3' -l version
complete -c 'phpize8.3' -s v -d 'Prints API version information SEE ALSO php (1) VERSION INFORMATION This manp…'

