# phpize.default
# Autogenerated from man page /usr/share/man/man1/phpize.default.1.gz
complete -c 'phpize.default' -l clean -d 'Remove all created files'
complete -c 'phpize.default' -l help -d 'Prints usage information'
complete -c 'phpize.default' -l version
complete -c 'phpize.default' -s v -d 'Prints API version information SEE ALSO php (1) VERSION INFORMATION This manp…'

