# po2debconf
# Autogenerated from man page /usr/share/man/man1/po2debconf.1.gz
complete -c po2debconf -s h -l help -d 'Display a usage summary and exit'
complete -c po2debconf -s v -l verbose -d 'Process in verbose mode'
complete -c po2debconf -l podir -d 'Set directory for \\s-1PO\\s0 files'
complete -c po2debconf -s o -l output -d 'Set output filename (default is standard output)'

