# shtool-version
# Autogenerated from man page /usr/share/man/man1/shtool-version.1.gz
complete -c shtool-version -s v -l verbose -d 'Print verbose information during processing'
complete -c shtool-version -s l -l language -d 'Choose format of version file file'
complete -c shtool-version -s n -l name -d 'Name the program the version is maintained for'
complete -c shtool-version -s p -l prefix -s s -l set -d 'Set the version to version'
complete -c shtool-version -s e -l edit -d 'Interactively enter a new version'
complete -c shtool-version -s i -l increase -d 'When option ``-i\'\' is used, the current version in file is updated by increas…'

