# shtool-platform
# Autogenerated from man page /usr/share/man/man1/shtool-platform.1.gz
complete -c shtool-platform -s F -l format -d 'This option controls the output formatting of this program'
complete -c shtool-platform -s S -l sep -d 'This option sets the word separation string for the platform information stri…'
complete -c shtool-platform -s C -l conc -d 'This option sets the word concatenation string for the platform information s…'
complete -c shtool-platform -s L -l lower -d 'This options enforces conversion of the output to all lower case'
complete -c shtool-platform -s U -l upper -d 'This options enforces conversion of the output to all upper case'
complete -c shtool-platform -s v -l verbose -d 'This option enforces verbose versions of all expansion constructs in format s…'
complete -c shtool-platform -s c -l concise -d 'This option enforces concise versions of all expansion constructs in format s…'
complete -c shtool-platform -s n -l no-newline -d 'This option omits the usual trailing newline character in the output'
complete -c shtool-platform -s t -l type -d 'This option is a meta option which internally sets options -F, -S, -C, -L, -U…'
complete -c shtool-platform -s d -l debug -d 'This option enables some internal debugging messages'
complete -c shtool-platform -s V -l version -d 'This option outputs the version information of shtool platform only'

