# shtool-mkdir
# Autogenerated from man page /usr/share/man/man1/shtool-mkdir.1.gz
complete -c shtool-mkdir -s t -l trace -d 'Shows the actually involved shell commands'
complete -c shtool-mkdir -s f -l force -d 'Forced continuation and no complaints if directory already exists'
complete -c shtool-mkdir -s p -l parents -d 'Automatic parent directory creation'
complete -c shtool-mkdir -s m -l mode -d 'The directory mode applied to the directory, see chmod\\|(1)'
complete -c shtool-mkdir -s o -l owner -d 'The directory owner name or id applied to the directory, see chown\\|(1)'

