# shtoolize
# Autogenerated from man page /usr/share/man/man1/shtoolize.1.gz
complete -c shtoolize -s h -d 'Displays a short help page describing the usage of shtoolize'
complete -c shtoolize -s v -d 'Displays the version number of shtoolize/shtool'
complete -c shtoolize -s q -d 'Displays no processing information'

