# shtool-table
# Autogenerated from man page /usr/share/man/man1/shtool-table.1.gz
complete -c shtool-table -s F -l field-sep -d 'Separate columns using sep.  Default is \\f(CW\\*(C`:\\*(C\''
complete -c shtool-table -s w -l width -d 'Width of each column.  Default is 15 characters'
complete -c shtool-table -s c -l columns -d 'Number of columns.  Default is \\f(CW3'

