# shtool-tarball
# Autogenerated from man page /usr/share/man/man1/shtool-tarball.1.gz
complete -c shtool-tarball -s v -l verbose -d 'Display some processing information'
complete -c shtool-tarball -s t -l trace -d 'Enable the output of the essential shell commands which are executed'
complete -c shtool-tarball -s o -l output -d 'Output tarball to file tarball'
complete -c shtool-tarball -s c -l compress -d 'Pipe resulting tarball through compression program prog'
complete -c shtool-tarball -s d -l directory -d 'Sets the top-level directory into which the tarball unpacks'
complete -c shtool-tarball -s u -l user -d 'The user (owner) of files and directories in the tarball to user'
complete -c shtool-tarball -s g -l group -d 'The group of files and directories in the tarball to group'

