# shtool-subst
# Autogenerated from man page /usr/share/man/man1/shtool-subst.1.gz
complete -c shtool-subst -s v -l verbose -d 'Display some processing information'
complete -c shtool-subst -s t -l trace -d 'Enable the output of the essential shell commands which are executed'
complete -c shtool-subst -s n -l nop -d 'No operation mode'
complete -c shtool-subst -s w -l warning -d 'Show warning on substitution operation resulting in no content change on ever…'
complete -c shtool-subst -s q -l quiet -d 'Suppress warning on substitution operation resulting in no content change'
complete -c shtool-subst -s s -l stealth -d 'Stealth operation.  Preserve timestamp on file'
complete -c shtool-subst -s i -l interactive -d 'Enter interactive mode where the user has to approve each operation'
complete -c shtool-subst -s b -l backup -d 'Preserve backup of original file using file name extension ext'
complete -c shtool-subst -s e -l exec -d 'Specify sed\\|(1) command directly'

