# shtool-path
# Autogenerated from man page /usr/share/man/man1/shtool-path.1.gz
complete -c shtool-path -s s -l suppress -d 'Suppress output'
complete -c shtool-path -s r -l reverse -d 'Transform a forward path to a subdirectory into a reverse path'
complete -c shtool-path -s d -l dirname -d 'Output the directory name of str'
complete -c shtool-path -s b -l basename -d 'Output the base name of str'
complete -c shtool-path -s m -l magic -d 'Enable advanced magic search for "\\f(CW\\*(C`perl\\*(C\'\\*(L" and \\*(R"\\f(CW\\*(C…'

