# shtool-echo
# Autogenerated from man page /usr/share/man/man1/shtool-echo.1.gz
complete -c shtool-echo -s n -l newline -d 'By default, output is written to stdout followed by a \\*(L"newline\\*(R" (\\s-1…'
complete -c shtool-echo -s e -l expand -d 'If option -e is used, string can contain special "%x" constructs which are ex…'

