# shtool-mdate
# Autogenerated from man page /usr/share/man/man1/shtool-mdate.1.gz
complete -c shtool-mdate -s n -l newline -d 'By default, output is written to stdout followed by a \\*(L"newline\\*(R" (\\s-1…'
complete -c shtool-mdate -s z -l zero -d 'Pads numeric day and numeric month with a leading zero'
complete -c shtool-mdate -s s -l shorten -d 'Shortens the name of the month to a english three character abbreviation'
complete -c shtool-mdate -s d -l digits -d 'Use digits for month.  Default is to use a english name'
complete -c shtool-mdate -s f -l field-sep -d 'Field separator string between the day month year tripple'

