# shtool-scpp
# Autogenerated from man page /usr/share/man/man1/shtool-scpp.1.gz
complete -c shtool-scpp -s v -l verbose -d 'Display some processing information'
complete -c shtool-scpp -s p -l preserve -d 'Preserves ofile independent of the generated ``#line\'\' lines'
complete -c shtool-scpp -s f -l filter -d 'Apply one or more pre-processing sed\\|(1) filter commands (usually of type ``…'
complete -c shtool-scpp -s o -l output -d 'Output file name.  Default is \\f(CW\\*(C`lib. h\\*(C\''
complete -c shtool-scpp -s t -l template -d 'Template file name.  Default is \\f(CW\\*(C`lib. h. in\\*(C\''
complete -c shtool-scpp -s M -l mark -d 'Mark to be replaced by generated constructs'
complete -c shtool-scpp -s D -l define -d '\\s-1FIXME. \\s0 Default is \\f(CW\\*(C`cpp\\*(C\''

