# shtool-mkshadow
# Autogenerated from man page /usr/share/man/man1/shtool-mkshadow.1.gz
complete -c shtool-mkshadow -s v -l verbose -d 'Display some processing information'
complete -c shtool-mkshadow -s t -l trace -d 'Enable the output of the essential shell commands which are executed'

