# shtool-slo
# Autogenerated from man page /usr/share/man/man1/shtool-slo.1.gz
complete -c shtool-slo -s p -l prefix -d 'Vb 1     FIXME . Ve'
complete -c shtool-slo -o Ldir -d 'Directory where libraries are searched in'

