# shtool-move
# Autogenerated from man page /usr/share/man/man1/shtool-move.1.gz
complete -c shtool-move -s v -l verbose -d 'Display some processing information'
complete -c shtool-move -s t -l trace -d 'Enable the output of the essential shell commands which are executed'
complete -c shtool-move -s e -l expand -d 'Expand asterisk in src to be used as "\\f(CW\\*(C`%\\*(C\'n" (where n is \\f(CW1,\\…'

