# x86_64-linux-gnu-gprofng
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gprofng.1.gz
complete -c x86_64-linux-gnu-gprofng -l version -d 'print the version number and exit'
complete -c x86_64-linux-gnu-gprofng -l help -d 'print usage information and exit'
complete -c x86_64-linux-gnu-gprofng -l check -d 'verify if the hardware and software environment is supported'
complete -c x86_64-linux-gnu-gprofng -l verbose -d 'enable (on) or disable (off) verbose mode; the default is "off"'

