# x86_64-linux-gnu-gp-display-html
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gp-display-html.1.gz
complete -c x86_64-linux-gnu-gp-display-html -l help -d 'print usage information and exit'
complete -c x86_64-linux-gnu-gp-display-html -l version -d 'print the version number and exit'
complete -c x86_64-linux-gnu-gp-display-html -l verbose -d 'enable/disable verbose mode that shows diagnostic messages about the processi…'
complete -c x86_64-linux-gnu-gp-display-html -s d -l debug -d 'control the printing of run time information to assist with troubleshooting, …'
complete -c x86_64-linux-gnu-gp-display-html -o hp -l --highlight-percentage -d 'a percentage value in the interval [0,100] to select and color code source li…'
complete -c x86_64-linux-gnu-gp-display-html -s o -l output -d 'use <dir-name> to store the results in; the default name is . /display. <n>'
complete -c x86_64-linux-gnu-gp-display-html -s O -l overwrite -d 'use <dir-name> to store the results in and overwrite any existing directory w…'
complete -c x86_64-linux-gnu-gp-display-html -s q -l quiet -d 'disable/allow the display of all warning, debug and verbose messages; if set …'
complete -c x86_64-linux-gnu-gp-display-html -s w -l warnings -d 'enable/disable run time warning messages; default is on'

