# x86_64-linux-gnu-gp-display-src
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gp-display-src.1.gz
complete -c x86_64-linux-gnu-gp-display-src -l version -d 'print the version number and exit'
complete -c x86_64-linux-gnu-gp-display-src -l help -d 'print usage information and exit'
complete -c x86_64-linux-gnu-gp-display-src -l verbose -d 'enable (on) or disable (off) verbose mode; the default is "off"'
complete -c x86_64-linux-gnu-gp-display-src -o func -d 'list all the functions from the given object'
complete -c x86_64-linux-gnu-gp-display-src -o source -d 'show the source code for item; the tag is used to differentiate in case of mu…'
complete -c x86_64-linux-gnu-gp-display-src -o disasm -d 'show the source code, interleaved with the disassembled instructions; the sam…'
complete -c x86_64-linux-gnu-gp-display-src -o outfile -d 'write results to file <filename>; a dash (-) writes to stdout; this is also t…'

