# x86_64-linux-gnu-gp-display-text
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gp-display-text.1.gz
complete -c x86_64-linux-gnu-gp-display-text -l version -d 'print the version number and exit'
complete -c x86_64-linux-gnu-gp-display-text -l help -d 'print usage information and exit'
complete -c x86_64-linux-gnu-gp-display-text -l verbose -d 'enable (on) or disable (off) verbose mode; the default is "off"'
complete -c x86_64-linux-gnu-gp-display-text -o script -d 'execute the commands stored in the script file; this feature may be combined …'

